name: Check Python Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "pypy3.9", "pypy3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.9"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          exclude: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Display Python Version
        run: |
          python --version
